### ISSUE TITLE
naive all_tables 

### ISSUE THREAD

**Issue by jjn1056** [jjn1056/DBIx-Class-Migration#103]
my @sources = _filter_private_sources($self->schema->sources);
    my $all_tables_path = catfile($fixture_conf_dir,'all_tables.json');
    _create_all_fixture_set($all_tables_path, @sources);

`@sources` is not certain to match what SchemaLoader does.  Maybe just need to use `_schema_from_database`

**Comment by KES777** [comment]
Actually you generate config correct (see [this](https://metacpan.org/pod/DBIx::Class::Fixtures#class)):

>Required attribute. Specifies the DBIx::Class object class you wish to dump.

There is no `roles_models` DBIx::Class, but `Permission` is. Thus config is correct.

**Comment by jjn1056** [comment]
Hi KES,

I'm sorry I can't explain to you in a way you understand it, but Fixtures has to be based on the current DB, not the Classes.  As a result we have to generate a DBIC schema on the fly via schema loader, and that means the Source names are going to reflect the automatic naming convention that Schemaloader uses, not your custom naming in your hand written DBIC classes.

This change was introduced years ago because it was the least bad option.  Its not ideal that the names are your your custom names, but this is a side effect of the flexibility that DBIC allows.  You could if you want constrain your custom classes to use the same naming convention as Schemaloader and that would avoid the mismatch.  But I can't force the fixture config sets to use the current schema since there are use cases when the deployed DB doesn't match (such as when you downgrade a DB for troubleshooting) and there are cases where people have custom plugins that do custom value inflation / deflation.  Its possible this indicates a flaw in the entire concept of the way DBIC::Fixtures works :)  However the current approach is in my mind the best balance of pro con.  I understand for your use case its all con, but if I changed this it would prevent other uses cases and break existing code.  So like I suggested I'd be willing to accept a patch that let you enable using the current DBIC classes as you wish with a flag.  that way I can preserve years of backward compatibility as well as meet your use case.

**Comment by KES777** [comment]
Is there a test already for mentioned cases?

**Comment by KES777** [comment]
Neither configuration works:
```
{
   "sets" : [
      {
         "class" : "Order",
         "quantity" : "all",
      },
      {
         "class" : "OrderDetails",
         "quantity" : "all",
      },
  ]
}
```
    DBIx::Class::Schema::source(): Can't find source for OrderDetails at /home/kes/work/projects/tucha/monkeyman/local/bin/dbic-migration line 4

```
{
   "sets" : [
      {
         "class" : "Order",
         "quantity" : "all",
      },
      {
         "class" : "order_details",
         "quantity" : "all",
      },
  ]
}
```
    DBIx::Class::Schema::source(): Can't find source for order_details at /home/kes/work/projects/tucha/monkeyman/local/bin/dbic-migration line 4

with fix above first configuration starts to work

**Comment by mohawk2** [comment]
This could only be implemented with options to leave existing behaviour still the default. It will need to be done as a PR, **with automated tests**. No tests, no merge.
