### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#104]
"No Database to populate!"

At code you have checked: `(my $self = shift)->dbic_dh->version_storage_is_installed`

I think it would be better to message: `Data base is not versioned. $ERROR`

where `$ERROR` will be:

  1. Can not populate.
  2. Can not make schema.
    etc.

**Comment by mohawk2** [comment]
This is similar to #99 (and also #95 which I'm leaving open for now) - closing for same reason.
