### ISSUE TITLE
Fixtures are restored at random order

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#106]
I have two fixtures:
```
$HASH1 = {
           id     => 4,
           parent_tariff_id
                  => 1,
         };
$HASH1 = {
           id     => 1,
           parent_tariff_id
                  => undef,
         };
```

As you can see first depend on second. Despite on the order of files (fixtures) how they are read from directory (see [this](https://metacpan.org/source/SKAUFMAN/DBIx-Class-Fixtures-1.001039/lib/DBIx/Class/Fixtures.pm#L1378)), the database population will `succeed` or `fail`:
```
	(in cleanup) DBIx::Class::Storage::DBI::_do_query(): DBI Exception: DBD::Pg::db do failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block at /home/kes/work/projects/safevpn/repo2/local/bin/dbic-migration line 4
DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with 'ERROR:  insert or update on table "tariffs" violates foreign key constraint "tariffs_fk_parent_tariff_id"
DETAIL:  Key (parent_tariff_id)=(1) is not present in table "tariffs".' at populate slice:
{
  id => 4,
  parent_tariff_id => 1,
} at /home/kes/work/projects/safevpn/repo2/local/bin/dbic-migration line 4
Makefile:169: recipe for target 'dbpopulate' failed
make: *** [dbpopulate] Error 255

```

The configuration for these fixtures is:
```
      {
         "class" : "Tariff",
         "ids" : [ 1, 4 ],
      },
```

It seems your modules should incorporate in some way with `DBIx::Class::Fixtures` and pass the order how fixtures should be restored

**Comment by jjn1056** [comment]
This is related to DBIC::Fixtures, not ::Migration but I don't think we can do anything about it.  Fixtures are not certain to load in an order that respect dependencies (and this isn't even possible since you can create circular dependencies).

The only workable approach is to disable constraints so that you can load in whatever order.  Fixtures does this properly for MySQL but Postgresql makes it very hard to do this.  I have a possible approach that I can share and we can see if it belongs in Fixtures.  Let me know if you are interested.

**Comment by KES777** [comment]
not now. thank you.

for readers: https://metacpan.org/pod/DBIx::Class::Storage::DBI#with_deferred_fk_checks

**Comment by KES777** [comment]
Possible problem resolution is to use [`SET CONSTRAINT`](https://www.postgresql.org/docs/10/static/sql-set-constraints.html):
>SET CONSTRAINTS sets the behavior of constraint checking within the current transaction.  DEFERRED constraints are not checked until transaction commit. Each constraint has its own IMMEDIATE or DEFERRED mode.

[Article](https://begriffs.com/posts/2017-08-27-deferrable-sql-constraints.html#data-ingestion)

>Deferring constraints while loading data can make the process more convenient. For instance, deferred foreign keys allow tables to be loaded in any order, children before parents. This can accommodate data arriving out of order, from the network perhaps.

**Comment by mohawk2** [comment]
If not interested, closing. This certainly sounds like it ought to be fixed (ha!) in DBIC::Fixtures.
