### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#109]
[Here](https://metacpan.org/source/JJNAPIORK/DBIx-Class-Migration-0.060/lib/DBIx/Class/Migration/Script/Help/dump_named_sets.pod)

you describe `fixture_sets` option, but in the example use `fixture_set` (without `s`)

**Comment by KES777** [comment]
Same typo [here](https://metacpan.org/source/JJNAPIORK/DBIx-Class-Migration-0.060/lib/DBIx/Class/Migration/Script/Help/populate.pod)

**Comment by mohawk2** [comment]
In fact, both are correct. See in `::Script`:

```
has fixture_sets => (
  traits => [ 'Getopt' ],
  is=>'ro',
  isa=>'ArrayRef',
  default => sub { +['all_tables'] },
  cmd_aliases => 'fixture_set');
```

**Comment by KES777** [comment]
Maybe it will be better to use only one variant in documentation?
currently it is ambiguous
