### ISSUE TITLE
field names are not quoted

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#110]
for `upgrade` script migration field name is not quoted:

    ALTER TABLE users ADD CONSTRAINT users_email UNIQUE (email);

In same time the `deploy` migration if fine:
```
CREATE TABLE "users" (
  "id" serial NOT NULL,
  "email" character varying(128),
  PRIMARY KEY ("id"),
  CONSTRAINT "users_email" UNIQUE ("email"),
);
```

**Comment by KES777** [comment]
How to reproduce.

Try to run this with PostgreSQL:

    __PACKAGE__->add_unique_constraint([qw/ language_id group lexeme /]);

**Comment by mohawk2** [comment]
They are now.
