### ISSUE TITLE
Regression between 0.060 and 0.064

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#118]
After upgrading the `$(which dbic-migration) --force --schema_class HyperMouse::Schema --database PostgreSQL -Ilib prepare` command put `migrations` directory into current one instead of `share/migrations`.

The [documenation says](https://metacpan.org/pod/release/JJNAPIORK/DBIx-Class-Migration-0.060/lib/DBIx/Class/Migration.pm#OPTIONAL:-Specify-a-target_dir):

>If you leave this undefined we default to using the **share** directory in your distribution root.

**Comment by KES777** [comment]
fixtures still are read from `share/fixtures` directory as expected

**Comment by mohawk2** [comment]
For my own and others' future reference, I am using this to locate when it changed:

```
git rebase -i 0.060 -x "perl -Ilib -It/lib -MDBIx::Class::Migration::Script -MTest::More -e 'is(DBIx::Class::Migration::Script->new_with_options(schema_class => shift)->migration->dbic_dh->script_directory, shift)' Local::Schema $PWD/t/share/migrations; rm -f local-schema.db"
```

**Comment by mohawk2** [comment]
The commit that changed the behaviour was 3b6f242 (coerce target_dir to absolute to work right on 5.26+ - fix #96)

**Comment by KES777** [comment]
and it should be `abspath/share`

because target_dir now is defined and has absolute path, the default `share` is not appended

**Comment by mohawk2** [comment]
Thanks, I had figured that one out. You can work around this until I fix it by just saying `--target_dir share`, which will get absolutised and behave as before.

**Comment by mohawk2** [comment]
Released as 0.066.

**Comment by KES777** [comment]
Thank for fix.
The strange thing here is that it was half broken. Only `migrations` folder stopped to work and `fixtures` works fine. Thus `migrations` and `fixtures` take information about root absolute path from different sources.

I think we should pay attention for this, except only if that is by design.

**Comment by mohawk2** [comment]
I look forward to your PR adding tests to constrain the behaviour.
