### ISSUE TITLE
missed dependency

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#123]
on clean system I get next error when run `prepare` command:

     Can't load producer 'SQL::Translator::Producer::YAML' : Error loading SQL::Translator::Producer::YAML as SQL::Translator::Producer::YAML : Can't locate YAML.pm in @INC (you may need to install the YAML module)

My `cpanfile` is:

```
requires 'Carton';
requires 'Mojolicious';
requires 'Mojolicious::Plugin::PODRenderer';
requires 'DBD::Pg';                   # by Database
requires 'DBIx::Class', '==0.082841';
requires 'DBIx::Class::Migration';
```

**Comment by mohawk2** [comment]
This is a problem with https://github.com/frioux/DBIx-Class-DeploymentHandler - please report it there.
