### ISSUE TITLE
It's too difficult to see what has changed between database versions

### ISSUE THREAD

**Issue by willsheppard** [jjn1056/DBIx-Class-Migration#125]
A typical set of files generated when making a one-line change to the database might be:
```
MyApp/fixtures/14/conf/all_tables.json
MyApp/migrations/MySQL/deploy/14/001-auto-__VERSION.sql
MyApp/migrations/MySQL/deploy/14/001-auto.sql
MyApp/migrations/MySQL/deploy/14/002-populate.sql
MyApp/migrations/MySQL/downgrade/14-13/001-auto.sql
MyApp/migrations/MySQL/downgrade/14-13/002-populate.sql
MyApp/migrations/MySQL/upgrade/13-14/001-auto.sql
MyApp/migrations/MySQL/upgrade/13-14/002-populate.sql
MyApp/migrations/_source/deploy/14/001-auto-__VERSION.yml
MyApp/migrations/_source/deploy/14/001-auto.yml
```

The change being: SQL commands to remove one line of data from a lookup table.

Unfortunately it's not possible by simply diffing any two of these files to figure out what is that change, and equally our change management tool **git** also cannot determine the actual change.

**Feature request:**
It would be great to be able to see what the actual change in SQL (or YAML) is between two versions of the database. For example:
```
$ dbic-migration diff 13 14

< |       2 | FieldThatWasRemoved |
```

Or perhaps:
```
$ dbic-migration diff 13 14

< *************************** 2. row ***************************
< type_id: 2
<    name: FieldThatWasRemoved
```

Files `001-auto.sql` and `001-auto.yml` already contain a complete representation of the SQL table structure. If there were equivalent files for the data, then it would be trivial to diff them to find out what had changed.

**Comment by mohawk2** [comment]
https://metacpan.org/pod/distribution/SQL-Translator/script/sqlt-diff

**Comment by willsheppard** [comment]
That seems to be for schemas, but not data like lookup tables.

**Comment by mohawk2** [comment]
I don't understand: are you saying lookup tables aren't part of the schema?

**Comment by willsheppard** [comment]
No, I'm saying that the data in the lookup table isn't part of the schema. It's data.

**Comment by mohawk2** [comment]
I'm afraid this would require too much guesswork in code to successfully spot in a general way. Also it seems a bit like you're treating data differences as if they're schema differences, which they're really not. It seems to me that would be outside the scope of what this module is trying to achieve?

**Comment by jjn1056** [comment]
This is closed already but I wonder if its not something that should be in the underlying migration modules (DBIC::DeploymentHandler).
