### ISSUE TITLE
upgrading over two versions does not work

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#127]
when I prepare changes:

    ${MIGRATION_CMD} --force --schema_class ${APP_NAMESPACE} --database ${DB_TYPE} -Ilib prepare

next changes occur (notice: 135-137)

	1	modified:   lib/HyperMouse/Schema.pm
	2	modified:   lib/HyperMouse/Schema/Result/BankStatementDetail.pm
	3	new file:   share/fixtures/137/conf/accounting.json
	4	new file:   share/fixtures/137/conf/all_tables.json
	5	new file:   share/fixtures/137/conf/initial.json
	6	new file:   share/fixtures/137/conf/service.json
	7	new file:   share/fixtures/137/conf/timezone.json
	8	new file:   share/migrations/PostgreSQL/deploy/137/001-auto-__VERSION.sql
	9	new file:   share/migrations/PostgreSQL/deploy/137/001-auto.sql
	10	new file:   share/migrations/PostgreSQL/downgrade/137-135/001-auto.sql
	11	new file:   share/migrations/PostgreSQL/upgrade/135-137/001-auto.sql
	12	new file:   share/migrations/_source/deploy/137/001-auto-__VERSION.yml
	13	new file:   share/migrations/_source/deploy/137/001-auto.yml

but when I try to upgrade DB I get the error( notice: it tries 136-137):

	$(which dbic-migration) --schema_class HyperMouse::Schema --database PostgreSQL -Ilib upgrade
	Reading configurations from /home/kes/work/projects/tucha/monkeyman/share/fixtures/135/conf
	Can't open directory '/home/kes/work/projects/tucha/monkeyman/share/migrations/PostgreSQL/upgrade/136-137':
	No such file or directory at /home/kes/work/projects/tucha/monkeyman/local/lib/perl5/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 103.

This occur when schema version and database version differ

    $(which dbic-migration) --schema_class HyperMouse::Schema --database PostgreSQL -Ilib status
    Schema is 136
    Deployed database is 135

Would it be better if `prepare` command will be prohibited when schema version and deployed database are different?
Or, probably, `prepare` command should take schema version instead of deployed database version

**Comment by mohawk2** [comment]
Please re-open this once you have "steps to reproduce" from things on my computer, i.e. the test / examples.
