### ISSUE TITLE
MetaCPAN Tutorial links are broken

### ISSUE THREAD

**Issue by Rhinogradentia** [jjn1056/DBIx-Class-Migration#141]
Dear Contributors,

I tried to work throught the DBIx-Class-Migration tutorial on metacpan and only found dead links in https://metacpan.org/pod/DBIx::Class::Migration::Tutorial#NEXT-STEPS:-TABLE-OF-CONTENTS

Is there another source for this Tutorial or could those broken links please be repaired?

This would be really great.

Thanks a lot in advance,
Best,
Nadine

**Comment by eserte** [comment]
Also the standard MetaCPAN link to the distribution is broken: https://metacpan.org/release/DBIx-Class-Migration

However, this URL works: https://metacpan.org/release/JJNAPIORK/DBIx-Class-Migration-0.075
But the distribution name is colored grey which indicates that there might be a PAUSE indexing problem with the module.

**Comment by Rhinogradentia** [comment]
Hi eserte, 
thank you for the information - I will now close this.
Best,
Nadine

**Comment by willsheppard** [comment]
I think the "PAUSE indexing problem" referred to above won't be resolved by PAUSE. It will only be resolved by the maintainers of this repo adding the documentation modules to the correct place -- I have opened another issue for this: https://github.com/jjn1056/DBIx-Class-Migration/issues/144
