### ISSUE TITLE
all_tables Fixture includes Views

### ISSUE THREAD

**Issue by mulletboy2** [jjn1056/DBIx-Class-Migration#23]
I can't think of a sensible reason for the default behaviour, but I'm not convinced that one doesn't exist.

The 'all_tables' Fixture includes DBIx::Class::ResultSource::Views. These views aren't tables in the DB, so dump_all_sets fails - which necessitates editing all_tables config each time it's generated. There may be some config option I've missed that can get around this?

Looks like adding a check for table_class DBIx::Class::ResultSource::View in _sets_data_from_sources might fix it?

**Comment by mohawk2** [comment]
After very little time (in the grand scheme of things), I have merged this to `master`! Closing.
