### ISSUE TITLE
DBICM 0.040 tests fail on CentOS 6.4 perl-5.16.3

### ISSUE THREAD

**Issue by ddelazerda** [jjn1056/DBIx-Class-Migration#34]
I put the test output in this [gist](https://gist.github.com/ddelazerda/6599075). Let me know if you need more information.

**Comment by davehodg** [comment]
This is a bit smelly: 

make: warning:  Clock skew detected.  Your build may be incomplete.
make: Warning: File `Makefile' has modification time 5.5 s in the future

Can you get ntp running and get a correct clock?
