### ISSUE TITLE
Poor error message when passing --database without --dsn to `dbicm install`

### ISSUE THREAD

**Issue by osfameron** [jjn1056/DBIx-Class-Migration#40]
After preparing a migration for PostgreSQL with --database=PostgreSQL, I tried to run 

```
$ dbic-migration -Ilib install --database=PostgreSQL
```

This gives the error:

```
Reading configurations from /home/vagrant/MyApp/share/fixtures/1/conf/home/vagrant/MyApp/share/migrations/SQLite does not exist; please write/generate some SQL
```

Obviously my command can't work (I didn't give it any connection info) but it's very surprising that it ignores the --database flag entirely and complains about the default DB not having a prepared migration.

**Comment by mohawk2** [comment]
Please take a look at the linked commit - if you feel that's not clear in explaining the situation, feel free to reopen!
