### ISSUE TITLE
Documentation/better inference missing for what options are supported by --database

### ISSUE THREAD

**Issue by osfameron** [jjn1056/DBIx-Class-Migration#41]
```
$ dbic-migration -Ilib prepare --database=Pg
Can't locate SQL/Translator/Producer/Pg.pm in @INC
....
$ postgres?
Can't locate...
$ postgresql? FFS!
Can't locate...
# open web-browser, look on metacpan for what the actual plugin is called...
```

Perhaps a "Did you mean `PostgreSQL`?" functionality.  Otherwise a list of plugins, or a link to the SQLT list of said plugins would be useful.

**Comment by mohawk2** [comment]
`Module::Find` was in fact the key, but involved learning how to make `MooseX::Getopt::OptionTypeMap` play nicely. That was a struggle, as the comments added around the code now attest. It now works as one would expect, and will be released shortly.
