### ISSUE TITLE
can't install with option --to_version

### ISSUE THREAD

**Issue by fschwach** [jjn1056/DBIx-Class-Migration#42]
I recently upgraded to version 0.044.

Now I don't seem to be able to wipe out a database and re-install it to a specific version like this any more:

```
dbic-migration -Ilib --schema_class My::Schema --dsn DSN --database MySQL drop_tables
dbic-migration -Ilib --schema_class My::Schema --dsn DSN --database MySQL install --to_version 45
```

When I do this now, I get this message:

```
Since this database is not versioned, we will assume version 46
```

46 is the current $VERSION of my schema. Of course the database isn't versioned because the version table has been deleted but it just used to work like this and I can't see how else to do this other then by changing the $VERSION of my schema all the time. 
Thanks for your help!

**Comment by awitney** [comment]
I have just come across this problem (DBIx::Class::Migration v0.42). As mentioned above it does indeed still install the correct version of the database, however it seems to be installing the current version of fixtures. e.g. I install version 1 of the schema, but fixtures are being loaded from share/fixtures/2/.

Is it possible to switch off fixture loading in an install?

**Comment by mohawk2** [comment]
This is the same problem as #84, and is (I believe) fixed by the fix for that. Therefore closing.
