### ISSUE TITLE
Deprecation of Class::MOP::load_class dumping stack traces for all invocations

### ISSUE THREAD

**Issue by gmarler** [jjn1056/DBIx-Class-Migration#45]
Whenever you invoke dbic-migration now, you get a page long stack trace starting with this:

```
Class::MOP::load_class is deprecated at /usr/perl5/site_perl/5.18.1/sun4-solaris-thread-multi-64/Class/MOP.pm line 71.
        Class::MOP::load_class('DBIx::Class::Migration::RunScript::Trait::TargetPath') called at /usr/perl5/site_perl/5.18.1/MooseX/Traits/Pluggable.pm line 46
        eval {...} called at /usr/perl5/site_perl/5.18.1/MooseX/Traits/Pluggable.pm line 46
```

I see several other modules have had to update themselves to eliminate this annoyance.

**Comment by ediblenergy** [comment]
This sounds like you need to upgrade MooseX::Traits::Pluggable. @jjn1056 doesn't sound like an issue in DBIx::Class::Migration

**Comment by karenetheridge** [comment]
@gmarler make sure you run `moose-outdated`, and upgrade everything you see listed there.

**Comment by mohawk2** [comment]
@karenetheridge Thanks for the solution on this! Closing.
