### ISSUE TITLE
File::Copy minimum version too high

### ISSUE THREAD

**Issue by eserte** [jjn1056/DBIx-Class-Migration#50]
Currently the minimum File::Copy version is 2.30, see https://metacpan.org/source/JJNAPIORK/DBIx-Class-Migration-0.055/Makefile.PL#L29
But this module version is not available before perl 5.20.1, and is not a core module. So effectively you restrict your module to perl 5.20.1 and 5.20.2.

BTW, I think the problem with the "massive failure reports" is not the minimum versions, but something different. There was not a single pass on cpantesters since 0.048 (see http://matrix.cpantesters.org/?dist=DBIx-Class-Migration%200.055;maxver=1 ), and there are testers who install all new module versions on their systems.

**Comment by eserte** [comment]
> and is not a core module

I meant: is not a dual life module.

**Comment by schwern** [comment]
Just ran into this myself.

```
$ cpanm DBIx::Class::Migration
...
! Installing the dependencies failed: Installed version (2.26) of File::Copy is not in range '2.30'
! Bailing out the installation for DBIx-Class-Migration-0.056.
43 distributions installed

$ cpanm File::Copy
skipping R/RJ/RJBS/perl-5.20.0.tar.gz
```

**Comment by jegade** [comment]
f8f77dd1acf863d269c38739bffba3be5229bb8a / 0.057 fix the problem for me.
