### ISSUE TITLE
Can't add [MetaYAML] to dist.ini

### ISSUE THREAD

**Issue by davehodg** [jjn1056/DBIx-Class-Migration#58]
(I've picked up D::C::M as part of the CPAN PR challenge)

One of the whinges on cpants is that there's no META.YML file. Allegedly, this is as simple as adding [MetaYAML] to dist.ini. Doing this means dzil build throws a:

[DZ] attempt to add META.yml multiple times; added by: text from coderef added by @ConfigSlicer/MetaYAML (Dist::Zilla::Plugin::MetaYAML line 86); text from coderef added by MetaYAML (Dist::Zilla::Plugin::MetaYAML line 86)
aborting; duplicate files would be produced at /Users/daveh/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Dist/Zilla/App/Command/build.pm line 71.

dist.ini looks otherwise innocuous. Google, nor the error messages really help me.

Any ideas?

**Comment by mohawk2** [comment]
Since 0.060 now has a `META.yml` (https://metacpan.org/source/JJNAPIORK/DBIx-Class-Migration-0.060/META.yml) I will close this. Thanks!
