### ISSUE TITLE
Table names quoting when preparing a migration

### ISSUE THREAD

**Issue by ikapelyukhin** [jjn1056/DBIx-Class-Migration#66]
I have a field in my MySQL database named `order`, when the migration is generated the table name isn't quoted, which unsurprisingly causes a SQL syntax error when applying this migration.

I've tried adding `quote_names` parameter, but it seems to have no effect:

```
dbic-migration prepare --dsn=dbi:mysql:database=database -U user -P password --dbic_connect_attrs quote_names=1
```

Is there some other way to enable quoting? I guess it would have made sense if it was enabled by default. Otherwise it seems to be related to #63.

**Comment by abeverley** [comment]
+1 on quoting table names by default. I've run into several table-name-not-quoted problems, which are not fixed with ```quote-names=1```

**Comment by jjn1056** [comment]
We made some changes in the 0.058 release, please let me know if I can close this ticket or not.
