### ISSUE TITLE
Test::PostgreSQL 1.20 breaks DBIx::Class::Migration

### ISSUE THREAD

**Issue by gmarler** [jjn1056/DBIx-Class-Migration#71]
Had to back off to Test::PostgreSQL 1.06 to escape from this problem that appears in Test::PostgreSQL 1.20:

$ dbic-migration -Ilib status

WARNING: using $Test::PostgreSQL::Defaults is DEPRECATED. Use Test::PostgreSQL->new( extra_initdb_args => ... ) instead. at /usr/perl5/site_perl/5.22.0/Test/PostgreSQL.pm line 25.

WARNING: using $Test::PostgreSQL::Defaults is DEPRECATED. Use Test::PostgreSQL->new( extra_postmaster_args => ... ) instead. at /usr/perl5/site_perl/5.22.0/Test/PostgreSQL.pm line 25.
Value "15432\n" did not pass type constraint "Maybe[Int]" (in $args->{"port"}) at (eval 1227) line 406
    Value "15432\n" did not pass type constraint "Maybe[Int]" (in $args->{"port"})
    Value "15432\n" is defined
    "Maybe[Int]" constrains the value with "Int" if it is defined
    Value "15432\n" did not pass type constraint "Int" (in $args->{"port"})

**Comment by mohawk2** [comment]
#76 converted DBICM to use `Test::Postgresql58`, released as 0.059 on 2017-10-17. Any problems, please open a new issue. Thanks for the report!
