### ISSUE TITLE
use of File::ShareDir::ProjectDistDir not advised

### ISSUE THREAD

**Issue by karenetheridge** [jjn1056/DBIx-Class-Migration#72]
Test::File::ShareDir is much simpler and less risky. See https://metacpan.org/pod/File::ShareDir::ProjectDistDir#DETERRENT

**Comment by mohawk2** [comment]
Thanks for the report!

So far, there is an absence of reported problems. Also, FSDPDD is currently not being used in a test-specific way, so I can't see how to use TFSD as a replacement. It seems to me DBICM is largely intended for use in dev, and somewhat manually, so I see the risks as minimal.

For these reasons, I am closing this issue for now. However, if issues DO arise, or even better you can suggest an actual migration strategy, I will be pleased to look anew!

**Comment by karenetheridge** [comment]
I will send a pull request then, because it is this user's opinion that FSDPDD should no longer be used in any circumstances.

**Comment by mohawk2** [comment]
Please do!
