### ISSUE TITLE
Can't open dir error when stick to `PostgreSQL` database

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#78]
I follow the guide and use `--database PostgreSQL` options in all commands

After this one I got error:
```
$ dbic-migration --schema_class MyApp::Schema --database PostgreSQL -Ilib install
Since this database is not versioned, we will assume version 1
Reading configurations from /home/kes/work/projects/myapp.io/myapp/share/fixtures/1/conf
Can't opendir($fh, '/home/kes/work/projects/myapp.io/myapp/share/migrations/SQLite/deploy/1'): No such file or directory at /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 109
DBIx::Class::Storage::TxnScopeGuard::DESTROY(): A DBIx::Class::Storage::TxnScopeGuard went out of scope without explicit commit or error. Rolling back. at /home/kes/perl5/perlbrew/perls/perl-5.24.0/bin/dbic-migration line 0
```

Here `DBIx::Class::Migration` tries to process `SQLite` despite on ` --database PostgreSQL`

**Comment by KES777** [comment]
Also I have notice when I use `--database PostgreSQL --database SQLite` option the `myapp-schema.db` file is not created on `prepare` step. But when I use `--database PostgreSQL` alone it is created

**Comment by jjn1056** [comment]
I think you need to spell it  &#39;Postgresql&#39; but am away from desk.  Check that and let me know

**Comment by KES777** [comment]
```
$ dbic-migration --schema_class ArtCoin::Schema --database Postgresql -Ilib prepare
Can't locate SQL/Translator/Producer/Postgresql.pm in @INC (you may need to install the SQL::Translator::Producer::Postgresql module) (@INC contains: lib /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/x86_64-linux /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0 /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0/x86_64-linux /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0 .) at /home/kes/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/DBIx/Class/Migration/Script.pm line 232.
```

I spell it as package name  [SQL::Translator::Producer::PostgreSQL](https://github.com/jjn1056/DBIx-Class-Migration/issues/41#issuecomment-30681196)

**Comment by KES777** [comment]
I think this error because of [dsn](http://search.cpan.org/~jjnapiork/DBIx-Class-Migration-0.058/lib/DBIx/Class/Migration/Script.pm#dsn)

>These three commandline flags describe how to connect to a target, physical database, where we will deploy migrations and fixtures. If you don't provide them, we will automatically deploy to a DBD::SQLite managed database located at "target_dir".

I think here you should warn about that some default are used. And in my case `--database PostgreSQL` you should die with message that it requires to setup appropriate ENV variables or options. Myabe show this link: http://search.cpan.org/~jjnapiork/DBIx-Class-Migration-0.058/lib/DBIx/Class/Migration/Script.pm#username and guideline to resolve problem.

**Comment by KES777** [comment]
It will be good to mention about such ENV variables and options [here](http://search.cpan.org/~jjnapiork/DBIx-Class-Migration-0.058/lib/DBIx/Class/Migration/Tutorial/FirstMigration.pod#Prepare_migration_files) at the end of paragraph like:

    MySQL schema requires you to supply dsn/username/password bla-bla-bla

**Comment by mohawk2** [comment]
I think it's sufficiently obvious that DSNs, usernames etc should be supplied. And yes, the producer is called `PostgreSQL`, although now if you give a wrong one, you get told which ones are right!
