### ISSUE TITLE
Fixtures configuration file is not copied from last version

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#82]
At [coping step](https://github.com/jjn1056/DBIx-Class-Migration/blob/master/lib/DBIx/Class/Migration.pm#L316) the default configuration file is prepared so last configuration [never copied](https://github.com/jjn1056/DBIx-Class-Migration/blob/master/lib/DBIx/Class/Migration.pm#L279)

**Comment by mohawk2** [comment]
If you don't give me a set of steps from the start that I can reproduce a problem, I can't fix it. I'm not even asking you to make an automated test. Closing until that changes.
