### ISSUE TITLE
FR: implement drop_procedures, drop_triggers

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#83]
Schema may have procedures and triggers.

Please implement method to clear them all, like drop_tables

**Comment by KES777** [comment]
Also here a small inconsistency: 
drop_tables also drop `dbix_class_deploaymenthandler_versions` table
so `stats` shows:

```
$(which dbic-migration) --schema_class ArtCoin::Schema --database PostgreSQL -Ilib status
Schema is 18
Database is not currently installed
```

Try to deploy new database case error:

    ERROR:  function "xxxxxx" already exists with same argument types

**Comment by mohawk2** [comment]
See `t/upgrade-downgrade-sqlite.t` for how to do Perl to make these things happen.
