### ISSUE TITLE
Can't find source for XXX

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#87]
When trying to dump data I get error: `Can't find source for `

I dig a bit and think you should pass whole `$shema` instead of just `$name`

More info [here on SO](https://stackoverflow.com/a/46073384/4632019)

**Comment by KES777** [comment]
Passing `$schema` instead of `$name` in making schema do not fix the problem.
it  seems problem is with `App::Schema0` namespace. Loader did not find resultset for this namespace

**Comment by jjn1056** [comment]
try to write me a test case and send a pull request on the test case.  If you give me a broken test case I can likely fix the issue

**Comment by KES777** [comment]
duplicate https://github.com/jjn1056/DBIx-Class-Migration/issues/101
