### ISSUE TITLE
Feature request: Allow to use DBIx::Class::EasyFixtures

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#88]
It seems that [DBIx::Class::EasyFixture](https://metacpan.org/pod/DBIx::Class::EasyFixture) is more handy in compare to [DBIx::Class::Fixtures](https://metacpan.org/pod/DBIx::Class::Fixtures)

**Comment by jjn1056** [comment]
@KES777 this is a pretty big change, feel free to map out how it would work.

**Comment by mohawk2** [comment]
The EasyFixture module describes itself as "alpha" state. Until that changes, and until you are willing to describe the material benefits of making such a big change, together with a specific plan for making it, I need to close this issue. Feel free to re-open it when ready :-)
