### ISSUE TITLE
Configuration is read from different version

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#90]
```
$make dbdeploy 
$(which dbic-migration) --schema_class App::Schema --database PostgreSQL -Ilib install --to_version 20
Since this database is not versioned, we will assume version 21
Reading configurations from /home/kes/work/projects/safevpn/repo2/share/fixtures/21/conf
$ make dbstatus
$(which dbic-migration) --schema_class App::Schema --database PostgreSQL -Ilib status
Schema is 21
Deployed database is 20
```

Because I provide `--to_version` parameter I expect that configurations are read from version `20`
But deployed database version is 20.

That is ambiguous to see the warning message:
```
Since this database is not versioned, we will assume version 21
Reading configurations from /home/kes/work/projects/safevpn/repo2/share/fixtures/21/conf
```

What is coming on here? please fix messages

**Comment by mohawk2** [comment]
If you don't give me a set of steps from the start that I can reproduce a problem, I can't fix it. I'm not even asking you to make an automated test. Closing until that changes.

**Comment by KES777** [comment]
duplicate of #84
