### ISSUE TITLE
Reduce the requirement for DeploymentHandler to 0.002220

### ISSUE THREAD

**Issue by KES777** [jjn1056/DBIx-Class-Migration#91]
Because of [the issue](https://github.com/frioux/DBIx-Class-DeploymentHandler/issues/59) introduced in 0.002221 version things stops to work

please reduce require version to `0.002220` [here](https://github.com/jjn1056/DBIx-Class-Migration/commit/c06b839fab6a659d244029b7a5ba0e00fa0cb07b#diff-a580a87ff9da14b51504d149be8ecaffR30)

**Comment by KES777** [comment]
Fixed at 0.002222
https://github.com/frioux/DBIx-Class-DeploymentHandler/issues/59#issuecomment-355765650

**Comment by mohawk2** [comment]
Yes it should! Thanks.
