### ISSUE TITLE
Perl migrations are broken on 5.26

### ISSUE THREAD

**Issue by jonathancast** [jjn1056/DBIx-Class-Migration#96]
Just tried setting up a migration with a Perl script, under Perl 5.26.2.  This fails noisily:

    Can't locate sql/migrations/PostgreSQL/upgrade/3-4/002-set-full-name.pl in @INC (@INC contains: lib /home/vagrant/.perlbrew/libs/perl-5.26.1@greeter/lib/perl5/x86_64-linux /home/vagrant/.perlbrew/libs/perl-5.26.1@greeter/lib/perl5 /home/vagrant/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/x86_64-linux /home/vagrant/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1 /home/vagrant/perl5/perlbrew/perls/perl-5.26.1/lib/5.26.1/x86_64-linux /home/vagrant/perl5/perlbrew/perls/perl-5.26.1/lib/5.26.1) at (eval 1315) line 4.
     at /home/vagrant/.perlbrew/libs/perl-5.26.1@greeter/lib/perl5/Context/Preserve.pm line 43.

Adding `PERL_USE_UNSAFE_INC=1` to the command-line fixed the issue.

The solution is almost certainly just to find the relevant `do` call and add a `./` to the front of the file name involved.

**Comment by mohawk2** [comment]
I was just fixing the tests, and found this one myself. The tests now work when the `target_dir` is an absolute path; a relative one will give this error. Therefore, the `target_dir` needs to be coerced to being an absolute path, which will be straightforward using similar types stuff to the `--database` update in the very latest release!
